### ISSUE TITLE
Wiki link 'Troubleshooting the Windows shell extension for CudaText'

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_shell_extension#10]
https://wiki.freepascal.org/CudaText#Troubleshooting_the_Windows_shell_extension_for_CudaText

@dinkumoil Hope it's OK

**Comment by dinkumoil** [comment]
@Alexey-T 

I think simply copying my comment from that issue to the wiki is not a good idea, since it is strongly related to the original issue report of that user.

I wrote a more common version of the text, see this markdown file:

[TroubleshootingShellExtension.txt](https://github.com/dinkumoil/cuda_shell_extension/files/5905287/TroubleshootingShellExtension.txt)

Here's the preview of its content:

# Troubleshooting the Windows shell extension for CudaText

There may be rare cases where _CudaText_'s menu item shows up in Windows Explorer context menu but the entry's icon is missing and an error message states that the provided file name was not found.

## File sets information

If you download a 32 bit version of _CudaText_, you will notice that there are two sets of files belonging to the shell extension.

Set 1 consists of these files:

  * _cudatext_shell32.dll_
  * _install_shell32.cmd_
  * _uninstall_shell32.cmd_

Set 2 consists of these files:

  * _cudatext_shell64.dll_
  * _install_shell64.cmd_
  * _uninstall_shell64.cmd_

Since 32 bit versions of _CudaText_ can be run on both 32 bit and 64 bit versions of Windows, two sets of files are needed. Use set 1 if you run _CudaText_ on a 32 bit version and set 2 if you run it on a 64 bit version of Windows.

The download package of _CudaText_ 64 bit contains only set 2 since this version can only be run on a 64 bit version of Windows.

**Please note:** It is **not** possible to install the 32 bit version of the shell extension on 64 bit Windows or vice versa.


## Common information

The context menu item works for all types of files, folders, disk drives, desktop links to these items, the desktop background and the background of an Explorer window showing a folder's content. Other kinds of right-clicked items don't show the context menu item.

The context menu entry's icon is extracted from the file _cudatext.exe_, the absence of the icon indicates that _cudatext.exe_ wasn't found by the shell extension. That's also the reason for the error message mentioned above.


## Fixing installation error

**Please note:** In the following only the 64 bit version of the shell extension running on 64 bit Windows is dealt with. If you want to install the 32 bit shell extension on 32 bit Windows you have to select the appropriate file names.

In case a suitable item has been right-clicked and the icon is missing from the context menu item, it is possible to install the shell extension manually. To do that please follow the steps below.

At first ensure that all the files

  * _cudatext.exe_
  * _cudatext_shell64.dll_
  * _install_shell64.cmd_
  * _uninstall_shell64.cmd_

are stored in the same folder.

Start a Windows console with administrative permissions. If you don't know how to do that search the internet to learn it.

Use the `CD` command to navigate to the folder where the above files are stored (it should be your _CudaText_ folder). You should end up with a command prompt that looks for example like this:

  `C:\cudatext>`

Type the following command into your console window and hit _Enter_:

  `regsvr32 /u "<Path-to-CudaText-folder>\cudatext_shell64.dll"`

This uninstalls the failing shell extension. You should see a confirmation message that indicates a successful deregistration of the DLL.

Close all programs and log off or restart Windows. Login in again and ensure that the _CudaText_ context menu item has disappeared.

Start a Windows console with administrative permissions again and use the `CD` command to navigate to your _CudaText_ folder (the folder where the above files are stored).

Type the following command into your console window and hit _Enter_:

  `regsvr32 "<Path-to-CudaText-folder>\cudatext_shell64.dll"`

You should see a confirmation message that indicates a successful registration of the DLL. Check the Explorer context menu to see if there is a _CudaText_ menu item that has an icon. Right click for example a *.txt file and select _Open with CudaText_ from the context menu.

**Comment by Alexey-T** [comment]
Updated in https://wiki.freepascal.org/CudaText
wiki uses 'MediaWiki' format (and lexer).

**Comment by dinkumoil** [comment]
> wiki uses 'MediaWiki' format

I will try to remember next time.
