### ISSUE TITLE
Open folder?

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_shell_extension#5]
User wish: http://synwrite.sourceforge.net/forums/viewtopic.php?f=20&t=2532&sid=79b2aa1eb80

**Comment by Alexey-T** [comment]
About his wish 2- maybe we need cmd line option like -side=1 to show side panel, =0 to hide it? @kvichans

**Comment by dinkumoil** [comment]
Aside from the fact that I don't have any time to work on the shell extension, it's worth to say that at least under Windows 10 v1909 Prof. the context menu of a folder already contains an _Open with CudaText_ entry. If one clicks on it, _CudaText_ opens and adds the selected folder to the project manager side panel.

 Thus, changing the shell extension in a manner that it would send the paths of all files contained in a folder instead of the folder path itself to _CudaText_ would break the functionality mentioned above. Or do I miss something?

**Comment by Alexey-T** [comment]
I posted this reply to the forum topic, so user can reply (his post was in 18 July)
Closing...
