### ISSUE TITLE
No "open with CudaText" item for folders

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_shell_extension#7]
Win10 2004 x64, CudaText 1.112.1 x64

- run install_shell64.cmd
- sign out, sign in (apply shell info)
- rt-click on files-> Cud item is here (Sublime item too, Winrar item too, ESET too)
- rt-click on folder (many folders tried, usual ones with .pas files)-> no Cud item! (no Sublime item, Winrar is still here, ESET is here)

now I understand that user who told about missing Cud item on dirs.

@kvichans @iramsoft @jairo-martinez Do you confirm?

**Comment by JairoMartinezA** [comment]
Yes correct, currently "Open with CudaText" is just available with one file or many files. I suppose the development of @dinkumoil in  #2307 is only for files.

**Comment by dinkumoil** [comment]
I plan to enhance the context menu handler in a manner that it is able to display its context menu entry also for:

* folders
* the background of folders (the empty space beyond the file list)
* whole drives.

Since the _Project Manager_ plugin already processes folder paths, I will **not** pass the **list of files contained** in the selected folder(s)/drive(s) to CudaText. Instead I will solely pass the folder path(s) (for a drive this would be the path of its root folder).

This is the most consistent behaviour because it works the same as if one would drag'n drop a folder's/drive's icon to CudaText's icon.

I hope to release the new version at next weekend.

**Comment by Alexey-T** [comment]
Good to know, thanks in advance.

**Comment by JairoMartinezA** [comment]
I agree with the approach that **Project Manager** need to be who is in charge to manage the folder paths. Congrats @dinkumoil

**Comment by dinkumoil** [comment]
@Alexey-T , @Jairo-Martinez , @kvichans , @iRamSoft

I would like to announce the release of v1.1. The binaries can be downloaded [here](https://github.com/dinkumoil/cuda_shell_extension/releases).

@Alexey-T Since I've added some info to the installation/uninstallation scripts, please update them in _CudaText_'s deployment packages as well. You can download them [here](https://github.com/dinkumoil/cuda_shell_extension/tree/master/install).

Please test and give feedback about any bugs/misbehaviours. **But before read [this](https://github.com/dinkumoil/cuda_shell_extension#known-issues).**

**Comment by Alexey-T** [comment]
Thanks for this update. I put it to beta
http://www.uvviewsoft.com/c/

@tmsg-gh Pls see too
