### ISSUE TITLE
The specified file cannot be found

### ISSUE THREAD

**Issue by viktor02** [dinkumoil/cuda_shell_extension#9]
![изображение](https://user-images.githubusercontent.com/19672960/104094417-de6f9900-52a1-11eb-8ed5-9607b57488ba.png)
![02058](https://user-images.githubusercontent.com/19672960/104094430-f2b39600-52a1-11eb-89d5-872495c1eda9.png)
Error: `The specified file cannot be found`

I put the file `cudatext_shell64.dll` in the install folder, executed `install_shell64.cmd`, the item in the context menu appeared, however, it seems to me that it does not find the executable file `cudatext.exe`, which is installed in `C:\cudatext\`. 
How do I fix this?

**Comment by dinkumoil** [comment]
At first two questions you should answer, please:

1. What kind of item did you right-click when the above error message appeared? The context menu item works for all types of files, folders, disk drives, desktop links to these items, the desktop background and the background of an Explorer window showing a folder's content. Other kinds of right-clicked items should not show the context menu item. I tried to avoid it from appearing in case of right-clicking an unsuitable item but I might have missed some.
2. In your screenshot it seems like the _CudaText_ context menu entry has no icon. Is this correct? Since the icon is extracted from the file `cudatext.exe`, the absence of the icon would confirm that `cudatext.exe` wasn't found by the shell extension.

In case you right-clicked a suitable item (see question 1) and the icon is missing from the context menu item (see question 2) let's try to install the shell extension manually. To do that please follow the steps below.

At first ensure that all the files

* `cudatext.exe`
* `cudatext_shell64.dll`
* `install_shell64.cmd`
* `uninstall_shell64.cmd`

are stored in the same folder (I guess `C:\cudatext` in your case). Now execute `uninstall_shell64.cmd` by double-clicking it and confirm the UAC dialog (asking for admin rights) popping up. This uninstalls the failing shell extension. Close all programs and log off or restart Windows.

Login in again and ensure that the _CudaText_ context menu item has disappeared. If this is not the case stop at this point and come back to obtain further instructions.

Now start a Windows console with administrative rights. If you don't know how to do that search in Yandex or Google to learn it.

Now use the `CD` command to navigate to the folder where the above files are stored (I guess `C:\cudatext` in your case). You should end up with a command prompt that looks like
```
C:\cudatext>
```
Now type the following command into your console window:
```
regsvr32 "C:\cudatext\cudatext_shell64.dll"
```
You should see a confirmation message that indicates a successful registration of the DLL or an error message. In the latter case, please come back and post the original error message and its english translation here.

In case of success, check the Explorer context menu to see if there is a _CudaText_ menu item **that has an icon**. Right click for example a `*.txt` file and select `Open with CudaText` from the context menu.

**Comment by viktor02** [comment]
Thanks, apparently I didn't read that you need to run the file from the installation folder
